apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
type: Opaque
data:
  ivorysql-password: SGVsbG9AMTIz
  replicator-password: SGVsbG9AMTIz
  rewind-password: SGVsbG9AMTIz
# 默认密码：SGVsbG9AMTIz base64 decode后为 Hello@123